name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

# Define default permissions for all jobs
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Verify test semantics
        run: npm run test:verify
      - name: Run tests
        run: npm test

  # This job only runs basic tests that don't need external APIs
  basic-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    # Create basic .env file with dummy credentials
    - name: Create .env file with dummy values
      run: |
        echo "NODE_ENV=test" > .env
        echo "LOG_LEVEL=error" >> .env
        echo "OPENAI_API_KEY=dummy-key" >> .env
        echo "SUPABASE_URL=https://example.com" >> .env
        echo "SUPABASE_KEY=dummy-key" >> .env
    
    # Run tests that don't depend on real external services
    - name: Run unit tests
      run: npm run test:unit
    
    - name: Run integration tests
      run: npm run test:integration

  # This job only runs in secure contexts (pushes or PRs from same repo)
  # and tests external APIs
  api-tests:
    runs-on: ubuntu-latest
    # Only run this job for pushes or PRs from the same repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    # Create .env file with real secrets
    - name: Create .env file with credentials
      run: |
        echo "NODE_ENV=test" > .env
        echo "LOG_LEVEL=error" >> .env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env 
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
    
    # Run real API and E2E tests
    - name: Run real API tests
      run: npm run test:real-api || echo "API tests failed but continuing"
    
    - name: Run E2E tests
      run: npm run test:e2e || echo "E2E tests failed but continuing"

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npx eslint src/ tests/
      
    - name: Check Prettier formatting
      run: npx prettier --check "src/**/*.js" "tests/**/*.js" 